[package]
name = "rust-tutorial"
version = "0.1.0"
edition = "2021"

[dependencies]
rpassword = "7.3.1"
uuid = { version = "1.13.2", features = ["v4"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.105"